name: "ðŸŽ‰ Release"

on:
  workflow_dispatch:
    inputs: {}

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Task
        uses: go-task/setup-task@v1
      - uses: actions/checkout@v3
      - run: |
          npm install @semantic-release/exec @google/semantic-release-replace-plugin @semantic-release/git @semantic-release/changelog
      - run: |
          task release
          export VERSION=$(ls dist | head -n 1 | cut -d'-' -f3)
          task repo:update ARCH=x86_64 VERSION=$VERSION
          task repo:update ARCH=aarch64 VERSION=$VERSION
        env:
          SSH_KEY: ${{ secrets.BITBUCKET_SSH_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}